### PR TITLE
Rdflib 6.0 and json-ld fixes

### LINKED ISSUE #45: rdflib_jsonld breaks install, replace with RDFLib 6.0 integrated version
A big change in RDFlib 6.0 was integrating rdflib_jsonld into RDFlib itself: RDFLib/rdflib#1354

Due to this, the rdflib_jsonld project has been archived and is not maintained anymore: https://github.com/RDFLib/rdflib-jsonld#archived

Since rdflib_jsonld cannot be installed anymore with the newest version of setuptools, since it has use_2to3 set to true, see pypa/setuptools#2769, this makes OWL-RL uninstallable with JSON-LD with the newest version of setuptools.

I noticed this when trying to work on a PR for pySHACL to fix the same issue: https://github.com/RDFLib/pySHACL/issues/93

### PR DESCRIPTION
**Pull request by ashleysommer**
Fixes #45
Replaces #46

Changes:
* Bump min rdflib to v5.0.0
* Remove json-ld from requirements
  * OWL-RL imports rdflib_jsonld in a `try: except` wrapper anyway. Its an optional feature
* Detect if RDFLib 6.0+ is in use, if so set `json_ld_available=True` without importing the module.

### CODE REVIEW

**Comment by ashleysommer** [comment]
@nicholascar 
Can you please review and merge, though I'm not sure how to correctly put out a new OWL-RL release.

**Comment by nicholascar** [comment]
> Can you please review and merge...

Sure, will do a bunch of rdflib reviews tonight.

> ...though I'm not sure how to correctly put out a new OWL-RL release.

I've got access to OWL-RL on GitHub & PiPY, so I should be able to put updates through.

**Review by Panaetius — APPROVED** [review]
Thanks for this, this is a better solution than the one in https://github.com/RDFLib/OWL-RL/pull/46, I'll close that PR in favor of this one.

**Review by nicholascar — APPROVED** [review]

**Comment by nicholascar** [comment]
version tagged, readthedocs updated and PyPI version released: [5.2.2](https://pypi.org/project/owlrl/5.2.2/)

**Comment by ashleysommer** [comment]
Thanks Nick!
As a direct result of this:
* PySHACL v0.16.2 released
  * works with rdflib 5.0.0 or 6.0.0, works on python 3.6 or greater, works with built-in `rdflib_jsonld` or imported.
  * https://github.com/RDFLib/pySHACL/releases/tag/v0.16.2
* PySHACL v0.17.0 released
  * works only with rdflib 6.0.0 and above, works only with 3.7 and above, works only with built-in `rdflib_jsonld`.
  * https://github.com/RDFLib/pySHACL/releases/tag/v0.17.0

**Pull request merged**
